{% set name = "looseversion" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5de17b0286a6014380acbc2323b49c73d22b54d4aef8128c89964a320a259514

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3
    - pip
    - flit-core >=3.2,<4
  run:
    - python >=3

test:
  imports:
    - looseversion
  requires:
    - pip
    - pytest
  commands:
    - pip check

about:
  home: https://github.com/effigies/looseversion
  summary: Version numbering for anarchists and software realists
  description: |
    looseversion is a drop-in replacement for the original distutils.version.LooseVersion.
    It implements an identical interface and comparison logic to `LooseVersion`.
    The only major change is that a `looseversion.LooseVersion` is comparable to a
    `distutils.version.LooseVersion`, which means tools should not need to worry whether
    all dependencies that use LooseVersion have migrated.
  license: PSF-2.0
  license_file: LICENSE
  # doc_url: No docs at present. This is where we'd put them.
  dev_url: https://github.com/effigies/looseversion

extra:
  recipe-maintainers:
    - effigies
